// <auto-generated />
using FridgeServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FridgeServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180415183651_Update7")]
    partial class Update7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FridgeServer.Models.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long?>("Timeout");

                    b.Property<bool>("basic");

                    b.Property<bool>("groceryOrBought");

                    b.HasKey("Id");

                    b.ToTable("Grocery");
                });

            modelBuilder.Entity("FridgeServer.Models.MoreInformations", b =>
                {
                    b.Property<int>("MoreInformationsId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Bought");

                    b.Property<long?>("Date");

                    b.Property<int?>("GroceryId");

                    b.Property<long?>("LifeTime");

                    b.Property<int?>("No");

                    b.Property<string>("typeOfNo");

                    b.HasKey("MoreInformationsId");

                    b.HasIndex("GroceryId");

                    b.ToTable("MoreInformations");
                });

            modelBuilder.Entity("FridgeServer.Models.MoreInformations", b =>
                {
                    b.HasOne("FridgeServer.Models.Grocery")
                        .WithMany("MoreInformations")
                        .HasForeignKey("GroceryId");
                });
#pragma warning restore 612, 618
        }
    }
}
