// <auto-generated />
using System;
using FridgeServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FridgeServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181015093520_UsersGrocery_1")]
    partial class UsersGrocery_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("FridgeServer.Models.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long?>("Timeout");

                    b.Property<int?>("Userid");

                    b.Property<bool>("basic");

                    b.Property<bool>("groceryOrBought");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("Grocery");
                });

            modelBuilder.Entity("FridgeServer.Models.MoreInformations", b =>
                {
                    b.Property<int>("MoreInformationsId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Bought");

                    b.Property<long?>("Date");

                    b.Property<int?>("GroceryId");

                    b.Property<long?>("LifeTime");

                    b.Property<int?>("No");

                    b.Property<string>("typeOfNo");

                    b.HasKey("MoreInformationsId");

                    b.HasIndex("GroceryId");

                    b.ToTable("MoreInformations");
                });

            modelBuilder.Entity("FridgeServer.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SecretId");

                    b.Property<string>("firstname");

                    b.Property<string>("lastname");

                    b.Property<byte[]>("passwordHash");

                    b.Property<byte[]>("passwordSalt");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FridgeServer.Models.Grocery", b =>
                {
                    b.HasOne("FridgeServer.Models.User")
                        .WithMany("UserGroceries")
                        .HasForeignKey("Userid");
                });

            modelBuilder.Entity("FridgeServer.Models.MoreInformations", b =>
                {
                    b.HasOne("FridgeServer.Models.Grocery")
                        .WithMany("MoreInformations")
                        .HasForeignKey("GroceryId");
                });
#pragma warning restore 612, 618
        }
    }
}
